  
package vista;
 

import accesoADatos.CompraData;
import accesoADatos.DetalleCompraData;
import accesoADatos.ProductoData;
import accesoADatos.ProveedorData;
import entidades.Compra;
import entidades.DetalleCompra;
import entidades.Producto;
import entidades.Proveedor;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


public class FormularioDetalleCompra extends javax.swing.JInternalFrame {

    /**
     *  
     */
    
    private List <Proveedor> listaProveedor;
    private ProveedorData proveedorData;
    private List <Producto> listaProductos;
    private Producto producto;
    private ProductoData productoData;
    private Compra compra=null;
    private CompraData compraData;
    private DetalleCompra detalleCompra  ;
    private DetalleCompraData detalleCompraData;
    private DefaultTableModel modeloTabla = new DefaultTableModel();
    private DefaultTableModel modeloTablaProductos = new DefaultTableModel();
    private DefaultTableModel modeloTablaProveedor = new DefaultTableModel();
    
    
    
    public FormularioDetalleCompra() {
        initComponents();
        modeloTabla = new DefaultTableModel() {
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        
        modeloTablaProductos = new DefaultTableModel() {
            public boolean  isCellEditable (int row, int column) {
                return false;
            }
        };
        
        modeloTablaProveedor = new DefaultTableModel() {
            public boolean  isCellEditable (int row, int column) {
                return false;
            }
        };
        
        armarCabeceraTabla();
        armarCabeceraTablaCmpra();
        armarCabeceraTablaProveedor();
        proveedorData = new ProveedorData();
        productoData = new ProductoData();
        cargarProveedor();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel_Materiattulo = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jButton_salir = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1_listadoProductos = new javax.swing.JTable();
        jcomboBoxProveedorCompra = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable1_listadoDetalleDeCompras1 = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Detalle de compras a proveedores");
        setToolTipText("");

        jLabel_Materiattulo.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel_Materiattulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/compras (1).png"))); // NOI18N
        jLabel_Materiattulo.setText(" Detalle de compra");

        jButton_salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/salir.png"))); // NOI18N
        jButton_salir.setText("Salir");
        jButton_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_salirActionPerformed(evt);
            }
        });

        jTable1_listadoProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1_listadoProductos);

        jcomboBoxProveedorCompra.setToolTipText("");
        jcomboBoxProveedorCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcomboBoxProveedorCompraActionPerformed(evt);
            }
        });

        jLabel1.setText("Elija un proveedor");

        jTable1_listadoDetalleDeCompras1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTable1_listadoDetalleDeCompras1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(205, 205, 205)
                .addComponent(jLabel_Materiattulo, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(311, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton_salir, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(172, 172, 172))
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(71, 71, 71)
                        .addComponent(jcomboBoxProveedorCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 543, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 543, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel_Materiattulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jcomboBoxProveedorCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(60, 60, 60)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                .addGap(30, 30, 30)
                .addComponent(jButton_salir, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    
    private void jButton_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_salirActionPerformed
        // TODO add your handling code here:
        //se llama al metodo simplemente
        dispose();
    }//GEN-LAST:event_jButton_salirActionPerformed

    
    
    private void jcomboBoxProveedorCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcomboBoxProveedorCompraActionPerformed
        // TODO add your handling code here:
        limpiarTabla();
        limpiarTablaProducto();
        Proveedor provSeleccionado = (Proveedor) jcomboBoxProveedorCompra.getSelectedItem();
        int proveedorId  = provSeleccionado.getIdProvedor() ;
       List <DetalleCompra> listaDeCompraAProveedor =  detalleCompraData.ListarComprasAProveedor(proveedorId);
       Compra c1= new Compra(provSeleccionado, LocalDate.MIN, true);
      // ------------------------TERMINAR! 
    }//GEN-LAST:event_jcomboBoxProveedorCompraActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_salir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel_Materiattulo;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable1_listadoDetalleDeCompras1;
    private javax.swing.JTable jTable1_listadoProductos;
    private javax.swing.JComboBox<Proveedor> jcomboBoxProveedorCompra;
    // End of variables declaration//GEN-END:variables

      private void armarCabeceraTabla() {
        ArrayList<Object> filaCabecera = new ArrayList<>();
        filaCabecera.add("id de detalle de compra");
        filaCabecera.add("cantidad");
        filaCabecera.add("precio de costo");
        filaCabecera.add("id de compra");
        filaCabecera.add("id de producto");
        filaCabecera.add("estado");
        for (Object aux : filaCabecera) {
            modeloTabla.addColumn(aux);
        }
        jTable1_listadoProductos.setModel(modeloTabla);
    }
      
      
          private void armarCabeceraTablaCmpra() {
        ArrayList<Object> filaCabecera = new ArrayList<>();
        filaCabecera.add("id de detalle de compra");
        
        for (Object aux : filaCabecera) {
            modeloTabla.addColumn(aux);
        }
        jTable1_listadoProductos.setModel(modeloTabla);
    }
      
      
      private void armarCabeceraTablaProveedor() {
        ArrayList<Object> filaCabecera = new ArrayList<>();
        filaCabecera.add("id de producto");
        filaCabecera.add("nombre");
        filaCabecera.add("razon social");
        for (Object aux : filaCabecera) {
            modeloTablaProductos.addColumn(aux);
        }
        jTable1_listadoProductos.setModel(modeloTablaProductos);
    }
      
       private void limpiarTabla() {
        modeloTabla.setRowCount(0);
    }
       
          private void limpiarTablaProducto() {
        modeloTablaProductos.setRowCount(0);
    }
       
       
       
       private void cargarProveedor () {
           for (Proveedor proveedor : proveedorData.listarProveedores() ) {
               jcomboBoxProveedorCompra.addItem(proveedor);
           }
       }


   

    
    
    
    
}
