  
package vista;
 
 
import accesoADatos.ProductoData;
import entidades.Producto;
import java.util.List;
import javax.swing.JOptionPane;


public class FormularioAltaProducto extends javax.swing.JInternalFrame {

    /**
     * Creates new form FormularioProducto
     */
    
    private ProductoData productoData = new ProductoData();
    private Producto productoActual = null;
    private List <Producto> listaProducto;
    
    public FormularioAltaProducto() {
        initComponents();
        jButton_eliminar.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel_titulo = new javax.swing.JLabel();
        jLabel_codigoMat = new javax.swing.JLabel();
        jButton_buscar = new javax.swing.JButton();
        jTextField_cod = new javax.swing.JTextField();
        jLabel_nombre = new javax.swing.JLabel();
        jTextField_nombre = new javax.swing.JTextField();
        jLabel_descr = new javax.swing.JLabel();
        jTextField_descripcion = new javax.swing.JTextField();
        jLabel_estado = new javax.swing.JLabel();
        jCheckBox_Activo = new javax.swing.JCheckBox();
        jSeparator1 = new javax.swing.JSeparator();
        jButton_nuevo2 = new javax.swing.JButton();
        jButton_eliminar = new javax.swing.JButton();
        jButton_guardar = new javax.swing.JButton();
        jButton_salir = new javax.swing.JButton();
        jTextField_precio = new javax.swing.JTextField();
        jLabel_precio = new javax.swing.JLabel();
        jLabel_stock = new javax.swing.JLabel();
        jTextField_stock = new javax.swing.JTextField();
        jTextField_stockMINIMO = new javax.swing.JTextField();
        jLabel_stockMinimo = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Formulario de alta / búsqueda  de producto");
        setToolTipText("");

        jLabel_titulo.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel_titulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/productoalta.png"))); // NOI18N
        jLabel_titulo.setText("  Producto");

        jLabel_codigoMat.setText("Código: ");

        jButton_buscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/buscar.png"))); // NOI18N
        jButton_buscar.setText("Buscar");
        jButton_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_buscarActionPerformed(evt);
            }
        });

        jLabel_nombre.setText("Nombre");

        jTextField_nombre.setText(" ");
        jTextField_nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_nombreActionPerformed(evt);
            }
        });

        jLabel_descr.setText("Descripción:");

        jTextField_descripcion.setText(" ");
        jTextField_descripcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_descripcionActionPerformed(evt);
            }
        });

        jLabel_estado.setText("Activo:");

        jCheckBox_Activo.setSelected(true);
        jCheckBox_Activo.setText("Si");
        jCheckBox_Activo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox_ActivoActionPerformed(evt);
            }
        });

        jButton_nuevo2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/mas.png"))); // NOI18N
        jButton_nuevo2.setText("Nuevo");
        jButton_nuevo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_nuevo2ActionPerformed(evt);
            }
        });

        jButton_eliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/borrador.png"))); // NOI18N
        jButton_eliminar.setText("Eliminar");
        jButton_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_eliminarActionPerformed(evt);
            }
        });

        jButton_guardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/guardar-el-archivo.png"))); // NOI18N
        jButton_guardar.setText("Guardar");
        jButton_guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_guardarActionPerformed(evt);
            }
        });

        jButton_salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/salir.png"))); // NOI18N
        jButton_salir.setText("Salir");
        jButton_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_salirActionPerformed(evt);
            }
        });

        jTextField_precio.setText(" ");
        jTextField_precio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_precioActionPerformed(evt);
            }
        });

        jLabel_precio.setText("Precio:");

        jLabel_stock.setText("Stock:");

        jTextField_stock.setText(" ");
        jTextField_stock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_stockActionPerformed(evt);
            }
        });

        jTextField_stockMINIMO.setText(" ");
        jTextField_stockMINIMO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_stockMINIMOActionPerformed(evt);
            }
        });

        jLabel_stockMinimo.setText("Stock minimo :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jButton_nuevo2, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton_eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton_guardar, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton_salir, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel_titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(170, 170, 170))
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel_precio)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextField_precio, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel_estado)
                                .addGap(57, 57, 57)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField_stock, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jCheckBox_Activo)
                                    .addComponent(jTextField_stockMINIMO, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel_stock)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel_codigoMat)
                                .addGap(42, 42, 42)
                                .addComponent(jTextField_cod, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(133, 133, 133)
                                .addComponent(jButton_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel_descr)
                                    .addComponent(jLabel_nombre))
                                .addGap(28, 28, 28)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField_descripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 407, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel_stockMinimo))
                        .addGap(0, 37, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel_titulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_codigoMat)
                    .addComponent(jTextField_cod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_buscar))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_nombre)
                    .addComponent(jTextField_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_descr)
                    .addComponent(jTextField_descripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_precio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_precio))
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_stock)
                    .addComponent(jTextField_stock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_stockMinimo)
                    .addComponent(jTextField_stockMINIMO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_estado)
                    .addComponent(jCheckBox_Activo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_guardar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_nuevo2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_salir, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_buscarActionPerformed
        // TODO add your handling code here:
      
        try {
            Integer prodInt = Integer.parseInt(jTextField_cod.getText());
            productoActual = (Producto) productoData.buscarProducto(prodInt);
            if (productoActual!=null) {
                jTextField_nombre.setText(productoActual.getNombreProducto());
                jTextField_descripcion.setText( productoActual.getDescripcion() );
                jTextField_precio.setText(String.valueOf (productoActual.getPrecioActual() ) );
                jTextField_stock.setText(String.valueOf(productoActual.getStock()));
                jTextField_stockMINIMO.setText(String.valueOf(productoActual.getStockMinimo()));
                jCheckBox_Activo.setSelected(productoActual.isEstado() ); 
                jButton_eliminar.setEnabled(true);
            } else {
                 JOptionPane.showMessageDialog(this, "código ingresado no corresponde a un producto registrado");
                 limpiarCamposPantalla();
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Datos incorrectos, reintente nuevamente");
            e.printStackTrace();
            limpiarCamposPantalla();
        }
    }//GEN-LAST:event_jButton_buscarActionPerformed

    private void jTextField_nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_nombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_nombreActionPerformed

    private void jTextField_descripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_descripcionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_descripcionActionPerformed

    private void jButton_nuevo2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_nuevo2ActionPerformed
        // TODO add your handling code here:
//        limpiarCamposPantalla();
//        productoActual=null;
    }//GEN-LAST:event_jButton_nuevo2ActionPerformed

    private void jButton_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_eliminarActionPerformed
 
        if (productoActual!=null) {
            productoData.eliminarProducto(productoActual.getIdProducto() );
            productoActual=null;
            limpiarCamposPantalla();
        } else  {
            JOptionPane.showMessageDialog(this, "No hay un producto seleccionado");
        }
    }//GEN-LAST:event_jButton_eliminarActionPerformed

    private void jButton_guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_guardarActionPerformed
        
        try {
            String nombre = jTextField_nombre.getText();
            String descripcion = jTextField_descripcion.getText();
            Double precio = Double.parseDouble(jTextField_precio.getText().trim());
            Integer stock = Integer.parseInt(jTextField_stock.getText().trim());
            Integer stockMInimo = Integer.parseInt(jTextField_stockMINIMO.getText().trim());
            boolean activo = jCheckBox_Activo.isSelected();

            if (!nombre.isEmpty() && !descripcion.isEmpty()) {

                if (productoActual == null) {
                    productoActual = new Producto(nombre, descripcion, precio, stock, stockMInimo, activo);
                    productoData.regristrarProducto(productoActual);
                } else {
                    productoActual.setNombreProducto(nombre);
                    productoActual.setDescripcion(descripcion);
                    productoActual.setPrecioActual(precio);
                    productoActual.setStock(stock);
                    productoActual.setStockMinimo(stockMInimo);
                    productoActual.setEstado(activo);
                    productoData.modificarProducto(productoActual);
                }

            } else {
                JOptionPane.showMessageDialog(this, "No pueden existir campos vacios");
                return;
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Datos incorrectos, reintente nuevamente");
            e.printStackTrace();
            limpiarCamposPantalla();

    }//GEN-LAST:event_jButton_guardarActionPerformed
    }
    
    
    private void jButton_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_salirActionPerformed
        // TODO add your handling code here:
        //se llama al metodo simplemente
        dispose();
    }//GEN-LAST:event_jButton_salirActionPerformed

    private void jCheckBox_ActivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox_ActivoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox_ActivoActionPerformed

    private void jTextField_precioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_precioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_precioActionPerformed

    private void jTextField_stockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_stockActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_stockActionPerformed

    private void jTextField_stockMINIMOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_stockMINIMOActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_stockMINIMOActionPerformed

    
        private void limpiarCamposPantalla() {
       jTextField_cod.setText("");
       jTextField_stock.setText("");
        jTextField_nombre.setText("");
        jTextField_descripcion.setText("");
        jTextField_precio.setText("");
        jTextField_stockMINIMO.setText("");
        jCheckBox_Activo.setSelected(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_buscar;
    private javax.swing.JButton jButton_eliminar;
    private javax.swing.JButton jButton_guardar;
    private javax.swing.JButton jButton_nuevo2;
    private javax.swing.JButton jButton_salir;
    private javax.swing.JCheckBox jCheckBox_Activo;
    private javax.swing.JLabel jLabel_codigoMat;
    private javax.swing.JLabel jLabel_descr;
    private javax.swing.JLabel jLabel_estado;
    private javax.swing.JLabel jLabel_nombre;
    private javax.swing.JLabel jLabel_precio;
    private javax.swing.JLabel jLabel_stock;
    private javax.swing.JLabel jLabel_stockMinimo;
    private javax.swing.JLabel jLabel_titulo;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextField_cod;
    private javax.swing.JTextField jTextField_descripcion;
    private javax.swing.JTextField jTextField_nombre;
    private javax.swing.JTextField jTextField_precio;
    private javax.swing.JTextField jTextField_stock;
    private javax.swing.JTextField jTextField_stockMINIMO;
    // End of variables declaration//GEN-END:variables
}
