  
package vista;
 
import accesoADatos.CompraData;
import accesoADatos.DetalleCompraData;
import entidades.DetalleCompra;
import accesoADatos.ProductoData;
import accesoADatos.ProveedorData;
import accesoADatos.ProveedorProductoData;
import entidades.Compra; 
import entidades.Producto;
import entidades.Proveedor;
import java.sql.Date;
import java.time.LocalDate;
import java.time.ZoneId;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


public class FormularioAltaCompra extends javax.swing.JInternalFrame {

    /**
     *  
     */
    
    private CompraData compraData = new CompraData();
    private Compra compraActual = null;
    private DetalleCompra detCompra;
    private ProveedorData provData;
    private ProductoData prodData;
    private ProveedorProductoData ppData;
    private List <Proveedor> listaProveedor;
    private List <Producto> listaProducto; 
    private List <DetalleCompra> listaDetalleCompras=null; 
    private List <Compra> listaCompras=null; 
    private DetalleCompraData detalleCompraData;
    private DefaultTableModel modeloTabla;
    private DefaultListModel<DetalleCompra> modeloList=new DefaultListModel<>(); 
      
    public FormularioAltaCompra() {
        initComponents();
        provData = new ProveedorData();
        prodData=new ProductoData();
        detalleCompraData = new DetalleCompraData();
        listaProveedor =provData.listarProveedores();
        //listaProducto=prodData.listaProductos();
        
        cargarProveedores();
        //cargarProductos();
        armarCabecera();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel_Materiattulo = new javax.swing.JLabel();
        jLabel_codigoMat = new javax.swing.JLabel();
        jTextField_cod = new javax.swing.JTextField();
        jLabel_nombre = new javax.swing.JLabel();
        jTextField_cant = new javax.swing.JTextField();
        jLabel_estado = new javax.swing.JLabel();
        jCheckBox_Activo = new javax.swing.JCheckBox();
        jSeparator1 = new javax.swing.JSeparator();
        jButton_nuevo2 = new javax.swing.JButton();
        jButton_guardar = new javax.swing.JButton();
        jButton_salir = new javax.swing.JButton();
        jLabel_domicilio = new javax.swing.JLabel();
        jLabel_fecha = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        cBoxProducto = new javax.swing.JComboBox<>();
        jcBoxProveedor = new javax.swing.JComboBox<>();
        jLabel_fecha1 = new javax.swing.JLabel();
        jButton_eliminar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableCompra = new javax.swing.JTable();
        jButton_buscar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jListDetalle = new javax.swing.JList<>();
        jbAgregar = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Compras");
        setToolTipText("");

        jLabel_Materiattulo.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel_Materiattulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/compras (1).png"))); // NOI18N
        jLabel_Materiattulo.setText(" Compra");

        jLabel_codigoMat.setText("Código: ");

        jLabel_nombre.setText("Cantidad:");

        jTextField_cant.setText(" ");
        jTextField_cant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_cantActionPerformed(evt);
            }
        });

        jLabel_estado.setText("Activo:");

        jCheckBox_Activo.setSelected(true);
        jCheckBox_Activo.setText("Si");
        jCheckBox_Activo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox_ActivoActionPerformed(evt);
            }
        });

        jButton_nuevo2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/mas.png"))); // NOI18N
        jButton_nuevo2.setText("Nuevo");
        jButton_nuevo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_nuevo2ActionPerformed(evt);
            }
        });

        jButton_guardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/guardar-el-archivo.png"))); // NOI18N
        jButton_guardar.setText("Guardar");
        jButton_guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_guardarActionPerformed(evt);
            }
        });

        jButton_salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/salir.png"))); // NOI18N
        jButton_salir.setText("Salir");
        jButton_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_salirActionPerformed(evt);
            }
        });

        jLabel_domicilio.setText("Producto:");

        jLabel_fecha.setText("Fecha de compra: ");

        cBoxProducto.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        cBoxProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cBoxProductoActionPerformed(evt);
            }
        });

        jcBoxProveedor.setToolTipText("");
        jcBoxProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcBoxProveedorActionPerformed(evt);
            }
        });

        jLabel_fecha1.setText("Proveedor:");

        jButton_eliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/borrador.png"))); // NOI18N
        jButton_eliminar.setText("Eliminar");
        jButton_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_eliminarActionPerformed(evt);
            }
        });

        jTableCompra.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableCompra);

        jButton_buscar.setText("Buscar");
        jButton_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_buscarActionPerformed(evt);
            }
        });

        jScrollPane2.setViewportView(jListDetalle);

        jbAgregar.setText("Agregar");
        jbAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAgregarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(189, 189, 189)
                        .addComponent(jLabel_Materiattulo, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(136, 136, 136)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel_estado)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCheckBox_Activo)
                        .addGap(78, 78, 78)
                        .addComponent(jButton_nuevo2, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton_eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton_guardar, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton_salir, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel_fecha1)
                                                .addComponent(jLabel_codigoMat))
                                            .addGap(48, 48, 48))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addComponent(jLabel_fecha)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel_domicilio)
                                            .addComponent(jLabel_nombre))
                                        .addGap(55, 55, 55)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cBoxProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jcBoxProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField_cod, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jTextField_cant, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(45, 45, 45)
                                        .addComponent(jbAgregar)))
                                .addGap(132, 132, 132)
                                .addComponent(jButton_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(84, 84, 84))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel_Materiattulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_codigoMat)
                    .addComponent(jTextField_cod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_buscar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_fecha))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_fecha1)
                    .addComponent(jcBoxProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_domicilio)
                    .addComponent(cBoxProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_cant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_nombre)
                    .addComponent(jbAgregar))
                .addGap(23, 23, 23)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_nuevo2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_guardar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_salir, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_estado)
                    .addComponent(jCheckBox_Activo))
                .addGap(26, 26, 26))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_nuevo2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_nuevo2ActionPerformed
        // TODO add your handling code here:
        limpiarCamposPantalla();
        borrarFilas2();
        compraActual = null;
    }//GEN-LAST:event_jButton_nuevo2ActionPerformed

    private void jButton_guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_guardarActionPerformed
 
       try {
        // Validación de Campos
        Integer cantidad = Integer.parseInt(jTextField_cant.getText().trim());

        // Obtener otros valores necesarios
        Proveedor proveedor = (Proveedor) jcBoxProveedor.getSelectedItem();
        Producto producto = (Producto) cBoxProducto.getSelectedItem();
        LocalDate fechaCompra = jDateChooser1.getDate().toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
        boolean estado = jCheckBox_Activo.isSelected();
        
        Compra compra=new Compra(proveedor,fechaCompra,true);
        CompraData cData=new CompraData();
        int clave=cData.compraAProveedores(compra);
        compra.setIdCompra(clave);
        for (int i = 0; i < modeloList.getSize(); i++) {
            DetalleCompra elemento = modeloList.getElementAt(i);
            DetalleCompra detalle=new DetalleCompra();
            detalle.setProducto(elemento.getProducto());
            detalle.setCantidad(elemento.getCantidad());
            detalle.setPrecioCosto(elemento.getPrecioCosto());
            detalle.setCompra(compra);
            detalleCompraData.registrarDetalleCompra(detalle);
        }
        
        

//        // Guardar o Modificar la Compra
//        if (compraActual == null) {
//            compraActual = new Compra(proveedor, fechaCompra, estado);
//        } else {
//            compraActual.setProvedor(proveedor);
//            compraActual.setFecha(fechaCompra);
//            compraActual.setEstado(estado);
//            compraData.modificarCompra(compraActual);
//        }
//
//        // Guardar o Modificar el Detalle de la Compra
//        if (detCompra == null) {
//            detCompra = new DetalleCompra(cantidad, precio, compraActual, producto, estado);
//        } else {
//            detCompra.setCantidad(cantidad);
//            detCompra.setPrecioCosto(precio);
//            detCompra.setCompra(compraActual);
//            detCompra.setProducto(producto);
//            detCompra.setEstado(estado);
//            detalleCompraData.modificarDetalleCompra(detCompra);
//        }

        // Mensaje de Éxito
        JOptionPane.showMessageDialog(this, "Detalles de compras guardados correctamente");

    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Datos incorrectos, reintente nuevamente");
        e.printStackTrace();
        limpiarCamposPantalla();
    }



    }//GEN-LAST:event_jButton_guardarActionPerformed

    private void jButton_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_salirActionPerformed
        // TODO add your handling code here:
        //se llama al metodo simplemente
        dispose();
    }//GEN-LAST:event_jButton_salirActionPerformed

    private void jCheckBox_ActivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox_ActivoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox_ActivoActionPerformed

    private void jTextField_cantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_cantActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_cantActionPerformed

    private void jButton_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_eliminarActionPerformed
        int idCompra=Integer.parseInt(jTextField_cod.getText());
        compraData.eliminarCompra(idCompra);
        detalleCompraData=new DetalleCompraData();
        detalleCompraData.eliminarDetalleCompraC(idCompra);
        
//        if (compraActual!=null) {
//            ///---------------------------------------Necesario eliminar en ambas tablas y tablas anexadas?
//            compraData.eliminarCompra(compraActual.getIdCompra());
//            // compraData.eliminarCompra(compraActual.getIdProvedor() );
//            compraActual=null;
//            limpiarCamposPantalla();
//            JOptionPane.showMessageDialog(this, "Compra eliminado");
//        } else  {
//            JOptionPane.showMessageDialog(this, "No hay una compra seleccionado");
//        }
    }//GEN-LAST:event_jButton_eliminarActionPerformed

    private void jButton_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_buscarActionPerformed
        // TODO add your handling code here:
        borrarFilas();

        try {
            Integer cod = Integer.parseInt(jTextField_cod.getText());
            compraActual = compraData.buscarCompra(cod);

            if (compraActual != null) {
                int codCompra = compraActual.getIdCompra();
                listaDetalleCompras=detalleCompraData.listarDetallesCompra(codCompra);

                if (!listaDetalleCompras.isEmpty()) {
                   for(DetalleCompra aux: listaDetalleCompras){
                        
                        modeloTabla.addRow(new Object[]{
                        aux.getCompra().getFecha(),
                        aux.getCompra().getProveedor(),
                        aux.getProducto(),
                        aux.getCantidad(),
                        aux.getPrecioCosto()
                    });
                   }
                    
                } else {
                    JOptionPane.showMessageDialog(this, "No existe detalle de compra para el código ingresado");
                }
            } else {
                JOptionPane.showMessageDialog(this, "No existe compra para el código ingresado");
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Ingrese un código válido");
        } catch (Exception e) {
            e.printStackTrace();
        }

        //        try {
        //         materiaActual= materiaData.buscarMateria(Integer.parseInt(jTextField_codMateria.getText()));
        //
        //            if (materiaActual!=null) {
        //                jTextField_nombreMateria.setText(materiaActual.getNombre());
        //                jTextField_anioMateria1.setText( Integer.toString (materiaActual.getAnioMateria() ) );
        //                jCheckBox_Activo.setSelected(materiaActual.isActivo());
        //            } else {
        //                 JOptionPane.showMessageDialog(this, "código ingresado no corresponde a una materia registrada");
                //                 limpiarCamposPantalla();
                //            }
            //        } catch (Exception e) {
            //            JOptionPane.showMessageDialog(this, "Datos incorrectos, reintente nuevamente");
            //            e.printStackTrace();
            //            limpiarCamposPantalla();
            //        }

    }//GEN-LAST:event_jButton_buscarActionPerformed

    private void jbAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAgregarActionPerformed
        // TODO add your handling code here:
        Proveedor proveedor=(Proveedor)jcBoxProveedor.getSelectedItem();
        java.util.Date d1 = jDateChooser1.getDate();
        LocalDate f1 = d1.toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
        Compra c=new Compra(proveedor,f1,true);
        Producto p=(Producto)cBoxProducto.getSelectedItem();
        int cantidad=Integer.parseInt(jTextField_cant.getText().trim());
        double costo=p.getPrecioActual()*cantidad;
        System.out.println("Cantidad "+cantidad);
        System.out.println("Costo "+costo);
        System.out.println(c);
        System.out.println(p);
        DetalleCompra dcompra=new DetalleCompra(cantidad,costo,c,p,true);
        jListDetalle.setModel(modeloList);
        modeloList.addElement(dcompra);
    }//GEN-LAST:event_jbAgregarActionPerformed

    private void cBoxProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cBoxProductoActionPerformed
        // TODO add your handling code here:
        Producto p=(Producto)cBoxProducto.getSelectedItem();
    }//GEN-LAST:event_cBoxProductoActionPerformed

    private void jcBoxProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcBoxProveedorActionPerformed
        // TODO add your handling code here:
        cBoxProducto.removeAllItems();
        ppData=new ProveedorProductoData();
        Proveedor provSeleccionado=(Proveedor)jcBoxProveedor.getSelectedItem();
        listaProducto=ppData.buscarProductosProveedor(provSeleccionado.getIdProvedor());
        for (Producto producto : listaProducto) {
            cBoxProducto.addItem(producto);
        }
    }//GEN-LAST:event_jcBoxProveedorActionPerformed

    private void armarCabecera() {
    if (modeloTabla == null) {
            modeloTabla = new DefaultTableModel();
        }

        ArrayList<Object> filaCabecera = new ArrayList<>();
        filaCabecera.add("Fecha de compra");
        filaCabecera.add("Proveedor");
        filaCabecera.add("Producto");
        filaCabecera.add("Cantidad");
        filaCabecera.add("Precio");

        for (Object aux : filaCabecera) {
            modeloTabla.addColumn(aux);
        }

        jTableCompra.setModel(modeloTabla);
    }

    private void cargarCompras() {
//        for (Compras  : compr.verBomberos()) {
        for (Compra aux : listaCompras) {
            for (DetalleCompra det : listaDetalleCompras) {
                for (Producto p : listaProducto) {

                    modeloTabla.addRow(new Object[]{
                        det.getProducto(),
                        det.getCantidad(),
           det.getPrecioCosto(),
           p.getNombreProducto(),
           aux.getFecha(),
           aux.getProveedor()
       });
            
        } 
    }
}}
         

    private void limpiarCamposPantalla() {
        jTextField_cant.setText("");
        jTextField_cod.setText("");
        jCheckBox_Activo.setSelected(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<Producto> cBoxProducto;
    private javax.swing.JButton jButton_buscar;
    private javax.swing.JButton jButton_eliminar;
    private javax.swing.JButton jButton_guardar;
    private javax.swing.JButton jButton_nuevo2;
    private javax.swing.JButton jButton_salir;
    private javax.swing.JCheckBox jCheckBox_Activo;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel_Materiattulo;
    private javax.swing.JLabel jLabel_codigoMat;
    private javax.swing.JLabel jLabel_domicilio;
    private javax.swing.JLabel jLabel_estado;
    private javax.swing.JLabel jLabel_fecha;
    private javax.swing.JLabel jLabel_fecha1;
    private javax.swing.JLabel jLabel_nombre;
    private javax.swing.JList<DetalleCompra> jListDetalle;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTableCompra;
    private javax.swing.JTextField jTextField_cant;
    private javax.swing.JTextField jTextField_cod;
    private javax.swing.JButton jbAgregar;
    private javax.swing.JComboBox<Proveedor> jcBoxProveedor;
    // End of variables declaration//GEN-END:variables

    private void cargarProveedores() {
        for (Proveedor proveedor : listaProveedor) {
           jcBoxProveedor.addItem(proveedor);
        }
    }

    private void cargarProductos() {
        for (Producto producto : listaProducto) {
            cBoxProducto.addItem(producto);
        }
    }
    
    private void borrarFilas() {
        //devuelve la cant de fila = getRowCount, que va a ser usada como indice por eso se resta -1
        int indiceFila = modeloTabla.getRowCount() - 1;
        for (int i = indiceFila; i >= 0; i--) {
            modeloTabla.removeRow(i);
        }
    }
    
    private void borrarFilas2() {
        //devuelve la cant de fila = getRowCount, que va a ser usada como indice por eso se resta -1
        modeloList.clear();
    }
}
