 
package vista;

import accesoADatos.ProductoData;
import entidades.Producto;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class ListaProducto extends javax.swing.JInternalFrame {

    private DefaultTableModel modeloTabla;
    private ProductoData prodData = null ;

    /**
     * Creates new form ListaProducto
     */
    public ListaProducto() {
        initComponents();
        prodData = new ProductoData();
        modeloTabla = new DefaultTableModel() {
            public boolean isCellEditable(int row, int column) {
                // Devolver false para que todas las celdas no sean editables
                return false;
            }
        };
        cargarComboBox();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel_compra = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jcomboBoxProducto = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1_listadoProducto = new javax.swing.JTable();

        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Lista de productos ");

        jLabel_compra.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel_compra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/productoalta.png"))); // NOI18N
        jLabel_compra.setText("Listado de productos");

        jLabel1.setText("Elija un producto: ");

        jcomboBoxProducto.setToolTipText("");
        jcomboBoxProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcomboBoxProductoActionPerformed(evt);
            }
        });
        jcomboBoxProducto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jcomboBoxProductoKeyReleased(evt);
            }
        });

        jTable1_listadoProducto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1_listadoProducto);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 465, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel_compra)
                            .addComponent(jcomboBoxProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(73, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel_compra)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcomboBoxProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(46, 46, 46)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(157, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jcomboBoxProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcomboBoxProductoActionPerformed
        limpiarTabla();
        Producto productoSeleccionado = (Producto) jcomboBoxProducto.getSelectedItem();
        int idProductoSeleccionadoABuscarBaseDato = productoSeleccionado.getIdProducto();
        
        if (productoSeleccionado.equals(prodData.buscarProducto(idProductoSeleccionadoABuscarBaseDato))) {
            for (Producto aux : prodData.listaProductos()) {
                modeloTabla.addRow(new Object[]{
                    aux.getIdProducto(),
                    aux.getNombreProducto(),
                    aux.getDescripcion(),
                    aux.getPrecioActual(),
                    aux.getStock()
                });
            } 
        } 
         
    }//GEN-LAST:event_jcomboBoxProductoActionPerformed

    private void jcomboBoxProductoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jcomboBoxProductoKeyReleased
        // TODO add your handling code here:
        Producto productoTipeado = (Producto) jcomboBoxProducto.getSelectedItem();
        
        if (productoTipeado.equals(prodData.buscarProducto(WIDTH))) {
            
        }
    }//GEN-LAST:event_jcomboBoxProductoKeyReleased


            private void armarCabeceraTabla(){
            ArrayList<Object> filaCabecera=new ArrayList<>();
            filaCabecera.add("Id producto");
            filaCabecera.add("Producto");
            filaCabecera.add("Descripción");
            filaCabecera.add("Precio");
            filaCabecera.add("Stock");
            for(Object aux:filaCabecera){
                modeloTabla.addColumn(aux);
            }
            jTable1_listadoProducto.setModel(modeloTabla);
        }
            
            private void cargarComboBox () {
                for (Producto listaProducto : listaProductos) {
                    jcomboBoxProducto.addItem(listaProducto);
                }
            }
            
            private void limpiarTabla () {
                modeloTabla.setRowCount(0);
            }
            
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel_compra;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1_listadoProducto;
    private javax.swing.JComboBox<Producto> jcomboBoxProducto;
    // End of variables declaration//GEN-END:variables
}
