 
package vista;


import accesoADatos.ProductoData;
import entidades.Producto;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.AbstractTableModel;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.JTextComponent;

public class ListaProducto extends javax.swing.JInternalFrame {

    private DefaultTableModel modeloTabla;
 //   private List <Proveedor> listaProveedorProveedor=null;
    private ProductoData productoData  = null ;
    private List <Producto> listaProducto=null;
    /**
     * Creates new form ListaProveedor
     */
    public ListaProducto() {
        initComponents();
        productoData = new ProductoData();
        //seteo de tabla p/que no sea editable
        modeloTabla = new DefaultTableModel() {
            public boolean isCellEditable(int row, int column) {
                 return false;
            }
        };
        cargarComboBox();
        armarCabeceraTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel_compra = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jcomboBoxProducto = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1_listadoProducto = new javax.swing.JTable();
        jTextField1_BusquedaProducto = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jBmostrar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Lista de productos disponibles ");

        jLabel_compra.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel_compra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/productoalta.png"))); // NOI18N
        jLabel_compra.setText("Listado de productos");

        jLabel1.setText("Escriba el nombre del producto: ");

        jcomboBoxProducto.setEditable(true);
        jcomboBoxProducto.setToolTipText("");
        jcomboBoxProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcomboBoxProductoActionPerformed(evt);
            }
        });

        jTable1_listadoProducto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1_listadoProducto);

        jTextField1_BusquedaProducto.setToolTipText("escriba para buscar coincidencias");
        jTextField1_BusquedaProducto.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTextField1_BusquedaProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1_BusquedaProductoActionPerformed(evt);
            }
        });
        jTextField1_BusquedaProducto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField1_BusquedaProductoKeyReleased(evt);
            }
        });

        jLabel2.setText("Elija un producto: ");

        jBmostrar.setText("Mostrar");
        jBmostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBmostrarActionPerformed(evt);
            }
        });

        jLabel3.setText("Productos inactivos");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel_compra)
                .addGap(211, 211, 211))
            .addGroup(layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(24, 24, 24)
                        .addComponent(jTextField1_BusquedaProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jcomboBoxProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 465, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(jBmostrar)))
                .addContainerGap(64, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_compra)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1_BusquedaProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcomboBoxProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(62, 62, 62)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jBmostrar))
                .addContainerGap(49, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1_BusquedaProductoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1_BusquedaProductoKeyReleased
        // Limpia la tabla antes de agregar nuevas filas
        limpiarTabla();

        // Verificar lo ingresado está en la lista de  
        String textoIngresadoTf = jTextField1_BusquedaProducto.getText().trim();
        try {
            List<Producto> productoListCoincidentes = productoData.buscarProdPorCoincidencia(textoIngresadoTf);

            //  modelo de la tabla no sea nulo
            if (modeloTabla != null) {

                for (Producto producto : productoListCoincidentes) {
                    modeloTabla.addRow(new Object[]{
                        producto.getIdProducto(),
                        producto.getNombreProducto(),
                        producto.getDescripcion(),
                        producto.getPrecioActual(),
                        producto.getStock()
                    });
                }
            } else {
                JOptionPane.showMessageDialog(this, "No hay datos cargados. Debe dar de alta un proveedor a traves de formulario");
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Error, reintente nuevamente");
            ex.printStackTrace();
        }
    }//GEN-LAST:event_jTextField1_BusquedaProductoKeyReleased

    private void jTextField1_BusquedaProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1_BusquedaProductoActionPerformed
        // TODO add your handling code here:
       
//        busquedaPorCoincidencia();
    }//GEN-LAST:event_jTextField1_BusquedaProductoActionPerformed

    private void jcomboBoxProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcomboBoxProductoActionPerformed
        // TODO add your handling code here:
        // Limpiar la tabla antes de agregar nuevas filas
       limpiarTabla();
       limpiarCampos ();
         Producto prod = (Producto) jcomboBoxProducto.getSelectedItem();
         
         try {
  
                 for (Producto producto : productoData.buscarProductoLista(prod.getIdProducto())  ) {
                    modeloTabla.addRow(new Object[]{
                        producto.getIdProducto(),
                        producto.getNombreProducto(),
                        producto.getDescripcion(),
                        producto.getPrecioActual(),
                        producto.getStock()
                    });
                    
            } 
               
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Error, reintente nuevamente");
            
        }
    }//GEN-LAST:event_jcomboBoxProductoActionPerformed

    private void jBmostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBmostrarActionPerformed
        // TODO add your handling code here:
        limpiarTabla();
        cargarProductosInactivos();

    }//GEN-LAST:event_jBmostrarActionPerformed

    private void armarCabeceraTabla() {
        ArrayList<Object> filaCabecera = new ArrayList<>();
        filaCabecera.add("Id producto");
        filaCabecera.add("Producto");
        filaCabecera.add("Descripción");
        filaCabecera.add("Precio");
        filaCabecera.add("Stock");
        for (Object aux : filaCabecera) {
            modeloTabla.addColumn(aux);
        }
        jTable1_listadoProducto.setModel(modeloTabla);
    }

    private void cargarComboBox() {
        for (Producto aux : productoData.listaProductos()) {
            jcomboBoxProducto.addItem(aux);
        }
    }

    private void limpiarTabla() {
        modeloTabla.setRowCount(0);
        
    }
    
    private void limpiarCampos () {
        jTextField1_BusquedaProducto.setText("");
    }

 
    private void cargarProductosInactivos(){
        List<Producto> productosInactivos = productoData.listaProductosBaja();
        for (Producto productoI : productosInactivos){
        modeloTabla.addRow(new Object[]{
                          productoI.getIdProducto(),
                          productoI.getNombreProducto(),
                          productoI.getDescripcion(),
                          productoI.getPrecioActual(),
                          productoI.getStock(),
        });
    }}


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBmostrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel_compra;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1_listadoProducto;
    private javax.swing.JTextField jTextField1_BusquedaProducto;
    private javax.swing.JComboBox<Producto> jcomboBoxProducto;
    // End of variables declaration//GEN-END:variables
}
