 
package vista;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;

/**
 *
 * @author Erica
 */
public class MenuView extends javax.swing.JFrame {

    /**
     * Creates new form MeniView
     */
    public MenuView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCalendar1 = new com.toedter.calendar.JCalendar();
        ImageIcon iconoEscritorio = new ImageIcon(getClass().getResource("/recursos/imagenDesktop.jpg"));
        Image escritorioImagen = iconoEscritorio.getImage();
        jDesktopPrincipal = new javax.swing.JDesktopPane(){
            public void paintComponent(Graphics g) {
                super.paintComponent(g);
                g.drawImage(escritorioImagen, 0, 0, getWidth(), getHeight(), this);
            }
        };
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1_detalleCompra = new javax.swing.JMenu();
        jMenuItem1_detalleCompra = new javax.swing.JMenuItem();
        jMenuItem1_listaCompras = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem_altaProducto = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1_altaProveedor = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ProveMax - Gestión de ventas");

        jDesktopPrincipal.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jDesktopPrincipalLayout = new javax.swing.GroupLayout(jDesktopPrincipal);
        jDesktopPrincipal.setLayout(jDesktopPrincipalLayout);
        jDesktopPrincipalLayout.setHorizontalGroup(
            jDesktopPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 568, Short.MAX_VALUE)
        );
        jDesktopPrincipalLayout.setVerticalGroup(
            jDesktopPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 429, Short.MAX_VALUE)
        );

        jMenu1_detalleCompra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/transaccion.png"))); // NOI18N
        jMenu1_detalleCompra.setText(" Compras    ");
        jMenu1_detalleCompra.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N

        jMenuItem1_detalleCompra.setText("Comprar");
        jMenuItem1_detalleCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1_detalleCompraActionPerformed(evt);
            }
        });
        jMenu1_detalleCompra.add(jMenuItem1_detalleCompra);

        jMenuItem1_listaCompras.setText("Lista de compras");
        jMenuItem1_listaCompras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1_listaComprasActionPerformed(evt);
            }
        });
        jMenu1_detalleCompra.add(jMenuItem1_listaCompras);

        jMenuBar1.add(jMenu1_detalleCompra);

        jMenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/producto logo.png"))); // NOI18N
        jMenu3.setText("  Productos      ");
        jMenu3.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N

        jMenuItem_altaProducto.setText("Formulario de alta / busqueda de producto");
        jMenuItem_altaProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_altaProductoActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem_altaProducto);

        jMenuBar1.add(jMenu3);

        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/repartidor (2).png"))); // NOI18N
        jMenu2.setText(" Proveedores");
        jMenu2.setToolTipText("");
        jMenu2.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N

        jMenuItem1_altaProveedor.setText("Formulario alta / busqueda de proveedor");
        jMenuItem1_altaProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1_altaProveedorActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem1_altaProveedor);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPrincipal)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPrincipal)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1_listaComprasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1_listaComprasActionPerformed
        // TODO add your handling code here:
        jDesktopPrincipal.removeAll();
        jDesktopPrincipal.repaint();
        ListaProveedores listaProveedores = new ListaProveedores();
        listaProveedores.setVisible(true);
        jDesktopPrincipal.add(listaProveedores);
        jDesktopPrincipal.moveToFront(listaProveedores);
        listaProveedores.getContentPane().setBackground(new Color(232, 248, 245  ));
    }//GEN-LAST:event_jMenuItem1_listaComprasActionPerformed

    private void jMenuItem1_altaProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1_altaProveedorActionPerformed
        // TODO add your handling code here:
        jDesktopPrincipal.removeAll();
        jDesktopPrincipal.repaint();
        FormularioAltaProveedor formularioAltaProveedor = new FormularioAltaProveedor();
        formularioAltaProveedor.setVisible(true);
        jDesktopPrincipal.add(formularioAltaProveedor);
        jDesktopPrincipal.moveToFront(formularioAltaProveedor);
        formularioAltaProveedor.getContentPane().setBackground(new Color(209, 242, 235 ));
    }//GEN-LAST:event_jMenuItem1_altaProveedorActionPerformed

    private void jMenuItem_altaProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_altaProductoActionPerformed
        jDesktopPrincipal.removeAll();
        jDesktopPrincipal.repaint();
        FormularioAltaProducto formProducto = new FormularioAltaProducto ();
        formProducto.setVisible(true);
        jDesktopPrincipal.add(formProducto);
        jDesktopPrincipal.moveToFront(formProducto);
        formProducto.getContentPane().setBackground(new Color(227, 242, 253));
    }//GEN-LAST:event_jMenuItem_altaProductoActionPerformed

    private void jMenuItem1_detalleCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1_detalleCompraActionPerformed
        // TODO add your handling code here:
        jDesktopPrincipal.removeAll();
        jDesktopPrincipal.repaint();
        FormularioAltaCompra formularioAltaCompra = new FormularioAltaCompra();
        formularioAltaCompra.setVisible(true);
        jDesktopPrincipal.add(formularioAltaCompra);
        jDesktopPrincipal.moveToFront(formularioAltaCompra);
        formularioAltaCompra.getContentPane().setBackground(new Color(251, 238, 230 ));
    }//GEN-LAST:event_jMenuItem1_detalleCompraActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JCalendar jCalendar1;
    private javax.swing.JDesktopPane jDesktopPrincipal;
    private javax.swing.JMenu jMenu1_detalleCompra;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1_altaProveedor;
    private javax.swing.JMenuItem jMenuItem1_detalleCompra;
    private javax.swing.JMenuItem jMenuItem1_listaCompras;
    private javax.swing.JMenuItem jMenuItem_altaProducto;
    // End of variables declaration//GEN-END:variables
}
