
package vista;

import accesoADatos.ProductoData;
import accesoADatos.ProveedorData;
import accesoADatos.ProveedorProductoData;
import entidades.Producto;
import entidades.Proveedor;
import entidades.ProveedorProducto;
import java.util.List;


public class ProductoProveedor extends javax.swing.JInternalFrame {

    private List<Proveedor> listaProveedor =null;
    private List<Producto> listaProductos=null;
    private ProveedorData proData;
    private ProductoData pData;
    
    public ProductoProveedor() {
        initComponents();
        proData=new ProveedorData();
        pData=new ProductoData();
        cargarComboBox();
        cargarComboBox2();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jboxProveedor = new javax.swing.JComboBox<>();
        jcProducto = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Asociar = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel1.setText("Producto-Proveedor");

        jLabel2.setText("Proveedor");

        jLabel3.setText("Prodcuto");

        Asociar.setText("Asociar");
        Asociar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AsociarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(116, 116, 116)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Asociar)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(178, 178, 178)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1)
                            .addComponent(jcProducto, 0, 322, Short.MAX_VALUE)
                            .addComponent(jboxProveedor, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(169, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jboxProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(60, 60, 60)
                .addComponent(Asociar)
                .addContainerGap(355, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AsociarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AsociarActionPerformed
        // TODO add your handling code here:
        ProveedorProductoData ppData=new ProveedorProductoData();
        ProveedorProducto pp=new ProveedorProducto();
        Proveedor provElegido = (Proveedor) jboxProveedor.getSelectedItem();
        Producto prodElegido = (Producto) jcProducto.getSelectedItem();
        pp.setProveedror(provElegido);
        pp.setProducto(prodElegido);
        pp.setEstado(true);
        ppData.compraAProveedores(pp);
    }//GEN-LAST:event_AsociarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Asociar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JComboBox<Proveedor> jboxProveedor;
    private javax.swing.JComboBox<Producto> jcProducto;
    // End of variables declaration//GEN-END:variables
    
    private void cargarComboBox() {
        for (Proveedor aux : proData.listarProveedores()) {
            jboxProveedor.addItem(aux);
        }
    }
    
    private void cargarComboBox2() {
        for (Producto aux : pData.listaProductos()) {
            jcProducto.addItem(aux);
        }
    }


}
